[regexaliases]
#(?i)electronic music = Electronic
#(?i)electronicmusic = Electronic
#(?i)alt[\s-]?rock = Alternative Rock
#(?i)alternative rock = Alternative Rock
#(?i)alternative = Alternative Rock
#(?i)hip[\s-]?hop = Hip Hop
#(?i)hiphop = Hip Hop
#(?i)rap = Hip Hop
#(?i)r\s*&\s*b = R&B
#(?i)rhythm and blues = R&B
##(?i)drum[\s]*(?:&|and|n)[\s]*bass = Drum And Bass
#(?i)d(?:rum)?[&n]b = Drum And Bass
#(?i)dnb = Drum And Bass
#(?i)drum'n'bass = Drum And Bass
