[regexaliases]
# Common genres with variable spelling
electronic[\s-]?music? = electronic
alt[\s-]?rock|alternative(\srock)?|alternative|alt = alternative rock
hip[\s-]?hop|hiphop|rap = hip hop
down[ /-]*(beat|tempo?) = downtempo
^punk$ = punk rock
^la cumbia$ = cumbia
^italian$ = cantautorato
^indie$ = indie rock
.*film.* = soundtrack
.*brass.* = brass band
funky = funk

# Common genres with ampersands
^r[\s&]*b$|^r(hythm)?[ n/&]*b(lues)?$ = rhythm and blues
^d(rum)?[\s]*(&|and|n)?[\s]*b(ass)?$ = drum and bass
drill[ n/&]*bass = drill and bass
rock[ n/&]*roll = rock and roll

# Consistent delimiters
(c|k|j)[ /]*(folk|goth|hip hop|pop|rock|ska|trance) = \g<1> \g<2>
(euro(?!p[ae]+n?)|neo|post|tech(?!n[io]))[ /]*(\w+) = \g<1> \g<2>
(g?lo)[ /]*fi = \g<1>-fi
(glitch|hip|jazz|trip)[ /-]*hop = \g<1> hop
(p|g)[ /]*funk = \g<1>-funk
nu[/-]*(disco|jazz|metal|soul) = nu \g<1>
synth[ /-]+(\w+) = synth\g<1>

# Abbreviation related
alt(/|er*n(/|ati[fv](es?)?))? = alternative
avant(/|gard)? = avantgarde
prog+(/|r*es+(/|i[fv]e?)?)? = progressive
(?<!neo[ -])ps?y(/|ch(/|[aeo]l?del+i[ca]+)?)? = psychedelic
trad(/|ition(/|al)?)?-? = traditional


